### ISSUE TITLE
关于redirect

### ISSUE THREAD

**Issue by wangke1970** [hangsz/raft#3]
在redirect 中
if data['dst_id'] != self.id:
            logging.info('redirect: to ' + data['dst_id'])
            # logging.info('redirec to leader')
            self.send(data, self.peers[data['dst_id']])
            return None
在那个情况下出现

**Comment by hangsz** [comment]
现实中网络未必如设想的那样运行，尤其是数据中心交换机设备。
这个部分是个辅助功能，可有可无。
