### ISSUE TITLE
请问这份代码是否有可能把socket换成grpc呢？

### ISSUE THREAD

**Issue by li3cmz** [hangsz/raft#4]

**Comment by wangke1970** [comment]
这个用的是udp报文高速传输，grpc 是http2 使用grpc没有意义

**Comment by hangsz** [comment]
是的，udp简单易用，raft节点间消息本身就不怕丢。
客户端和raft leader之间的消息如果不是幂等的，可能会导致重复，不过我这里没关注这个问题。
是可以用grpc的，etcd用的就是grpc。
